# Generated by Django 4.0.3 on 2023-02-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_alter_invoice_invoice_no_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance_work_done',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='current_work_done',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='previous_work_done',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_work_done',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
